import {Row} from './types';

export const DATA: Row[] = [
  {
    id: '1',
    brand: 'BMW',
    model: 'X6',
    year: 2018,
    fuel: 'petrol',
    bodyType: 'SUV',
    price: 80000,
    mileage: 50000,
  },
  {
    id: '2',
    brand: 'BMW',
    model: 'i8',
    year: 2019,
    fuel: 'diesel',
    bodyType: 'Coupe',
    price: 120000,
    mileage: 30000,
  },
  {
    id: '3',
    brand: 'BMW',
    model: 'M8',
    year: 2018,
    fuel: 'petrol',
    bodyType: 'Sedan',
    price: 100000,
    mileage: 75000,
  },
  {
    id: '4',
    brand: 'Mercedes',
    model: 'GLA 200',
    year: 2019,
    fuel: 'petrol',
    bodyType: 'SUV',
    price: 40000,
    mileage: 90000,
  },
  {
    id: '5',
    brand: 'Mercedes',
    model: 'Benz S 500',
    year: 2021,
    fuel: 'petrol',
    bodyType: 'Sedan',
    price: 85000,
    mileage: 1000,
  },
  {
    id: '6',
    brand: 'Nissan',
    model: 'Skyline GTR',
    year: 2020,
    fuel: 'petrol',
    bodyType: 'Coupe',
    price: 90000,
    mileage: 60000,
  },
  {
    id: '7',
    brand: 'Nissan',
    model: 'Titan',
    year: 2018,
    fuel: 'diesel',
    bodyType: 'Pickup',
    price: 75000,
    mileage: 100000,
  },
  {
    id: '8',
    brand: 'Nissan',
    model: 'Micra K14',
    year: 2017,
    fuel: 'petrol',
    bodyType: 'Hatchback',
    price: 15000,
    mileage: 110000,
  },
  {
    id: '9',
    brand: 'Toyota',
    model: 'Camry 3.5',
    year: 2019,
    fuel: 'petrol',
    bodyType: 'Sedan',
    price: 35000,
    mileage: 40000,
  },
  {
    id: '10',
    brand: 'Toyota',
    model: 'Prius Prime',
    year: 2018,
    fuel: 'hybrid',
    bodyType: 'Sedan',
    price: 25000,
    mileage: 65000,
  },
  {
    id: '11',
    brand: 'Tesla',
    model: 'Roadster',
    year: 2021,
    fuel: 'electric',
    bodyType: 'Sedan',
    price: 220000,
    mileage: 500,
  },
  {
    id: '12',
    brand: 'Tesla',
    model: 'S',
    year: 2017,
    fuel: 'electric',
    bodyType: 'Hatchback',
    price: 60000,
    mileage: 120000,
  },
  {
    id: '13',
    brand: 'Chevrolet',
    model: 'Corvette',
    year: 2019,
    fuel: 'petrol',
    bodyType: 'Cabrio',
    price: 85000,
    mileage: 45000,
  },
  {
    id: '14',
    brand: 'MINI',
    model: 'Cooper Classic',
    year: 2021,
    fuel: 'petrol',
    bodyType: 'MVP',
    price: 30000,
    mileage: 1100,
  },
]

